# Generated by Django 2.1.1 on 2018-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Bu alan bos birakilabilir.', max_length=255, null=True)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='blogresimleri/blog.png', upload_to='blogresimleri/%Y/%m/%d')),
                ('slug', models.SlugField(help_text='Link, otomatik alinir, değiştirmeyiniz!!', max_length=80, null=True)),
                ('link', models.URLField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='blogvideoları/%Y/%m/%d')),
                ('about', models.TextField()),
            ],
        ),
    ]
