# Generated by Django 2.1.1 on 2018-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(upload_to='blogvideoları/%Y/%m/%d'),
        ),
    ]
