# Generated by Django 2.1.1 on 2018-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180918_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogvideoları/%Y/%m/%d'),
        ),
    ]
