# Generated by Django 2.1.1 on 2018-10-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181007_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='background_image',
        ),
    ]
