# Generated by Django 2.1.1 on 2018-10-07 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='haha'),
            preserve_default=False,
        ),
    ]
