# Generated by Django 2.1.1 on 2018-10-07 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
