# Generated by Django 2.1.1 on 2018-10-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Subtitle',
        ),
    ]
