# Generated by Django 2.1.1 on 2018-10-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AlterField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(default='blogresimleri/mexico.png', upload_to='blogresimleri/%Y/%m/%d'),
        ),
    ]
