# Generated by Django 2.1.1 on 2018-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181008_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background_image',
            field=models.ImageField(default='blogresimleri/mexico.jpg', upload_to='blogresimleri/%Y/%m/%d'),
        ),
    ]
